### ISSUE TITLE
On the use of optical flow

### ISSUE THREAD

**Issue by fupiao1998** [GewelsJI/GTNet#1]
Hello, thank you very much for your open source code.
I am puzzled about the optical flow in your work. I have the following questions:
First, as we all know, optical flow is a motion field between two frames. For a T-frame video, the obtained optical flow has T-1 frames. How to deal with the missing one frame in the model.
Second, by observing your dataloader, I found that the optical flow was read in the form of three channel RGB. So, in your code implementation, what kind of color coding method is used to store the optical flow when using RAFT. If you can open source the part of processing and storing the optical flow, that would be great, thank you very much!
Third, can you open source the code of the complete training process?

**Comment by WangXiao213** [comment]
Let me answer your question: First, during the data processing, we lost the last frame of the video sequence. Second, the RAFT method has introduced the generation and storage of optical flow graphs in detail. I suggest you look at the code carefully. Third, due to the limited space of ICIP, I failed to introduce the training process in detail. You can leave your email address and we will talk in detail.

**Comment by fupiao1998** [comment]
Hello, thank you very much for your reply. Regarding the problem of RAFT storing optical flow, my main doubt is that I don't know which encoding method is used for the optical flow stored in the model you are using. The general optical flow is the data structure of H, W, 2, and then can be stored in the format of .flo (sintel dataset) or .png (KITTI dataset). Then, if you store it in RGB, from the data structure of H, W, 2 to the data structure of H, W, 3, there are many different color mapping methods. I guess if you are using the encoding method of flow2img used in this line in RAFT. https://github.com/princeton-vl/RAFT/blob/master/demo.py#L31 ？
Thank you for your reply, and my email address is maoyuxin@mail.nwpu.edu.cn

**Comment by WangXiao213** [comment]
We are using the optical flow diagram generated by the RAFT method.

**Comment by WangXiao213** [comment]
We are using the optical flow(H,W,3) generated by the RAFT method.

**Comment by fupiao1998** [comment]
Ok thanks! let me try

**Comment by GewelsJI** [comment]
Hi, fupiao1998,

Thank you for your attention to our work first. This issue seems to be solved and I temporarily close it. 

Best regards,
Ge-Peng.
